import numpy as np


def brier_score_loss(y_true: np.ndarray, y_prob: np.ndarray) -> float: ...
def log_loss(y_true: np.ndarray, y_pred: np.ndarray) -> float: ...
def ndcg_score(y_true: np.ndarray, y_score: np.ndarray, k: int = 2) -> float: ...
